blank_issues_enabled: false
contact_links:
  - name: General TURTLE Robotics questions
    url: https://turtlerobotics.org/
    about: For general questions about TURTLE Robotics, go to the team website.
