name: build-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-sphinx-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Sphinx build
        run: sphinx-build docs/source _build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/

  deploy-to-gh-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-sphinx-site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
