name: docs-ci
on: [pull_request]

jobs:
  build-sphinx-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Sphinx build
        run: sphinx-build -W -b html docs/source _build
